import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.annotation.*;

@WebServlet(name = "matchin", urlPatterns = { "/matchin" })
@MultipartConfig(
  fileSizeThreshold = 1024 * 1024 * 1, // 1 MB
  maxFileSize = 1024 * 1024 * 10,      // 10 MB
  maxRequestSize = 1024 * 1024 * 100   // 100 MB
)
public class matchin extends HttpServlet {

  private String uploadDirectory;
  private String pythonScriptPath;

  @Override
  public void init(ServletConfig config) throws ServletException {
    super.init(config);
    uploadDirectory = config.getServletContext().getInitParameter("uploadDirectory");
    pythonScriptPath = "/opt/tomcat/webapps/ROOT/WEB-INF/classes/face_detect.py"; // Set the path to your Python script
  }

  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException{
    response.setContentType("text/html");
    PrintWriter out = response.getWriter();
    out.println("<html><head><title>matchin</title></head>");
    out.println("<body>");
    out.println("<form method='post' enctype='multipart/form-data'><input type='file' name='file' /><input type='submit' value='Upload' /></form>");
    out.println("</body></html>");
    out.close();
  }

  public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    // Write the file to the directory
    Part filePart = request.getPart("file");
    String fileName = filePart.getSubmittedFileName();
    filePart.write(uploadDirectory + File.separator + fileName);

    // Execute the Python script with the uploaded file name
    String command = "python3 " + pythonScriptPath + " " + uploadDirectory + File.separator + fileName;
    Process process = Runtime.getRuntime().exec(command);
    try {
      process.waitFor();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    // Send the user the new file generated by the script
    String outputFileName = fileName.split("\\.")[0] + "_output.jpg";
    File outputFile = new File(uploadDirectory + File.separator + outputFileName);
    response.setContentType("image/jpeg");
    response.setHeader("Content-Disposition", "attachment; filename=\"" + outputFileName + "\"");
    OutputStream out = response.getOutputStream();
    FileInputStream in = new FileInputStream(outputFile);
    byte[] buffer = new byte[4096];
    int length;
    while ((length = in.read(buffer)) > 0) {
      out.write(buffer, 0, length);
    }
    in.close();
    out.flush();
  }
}
